name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: node install
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: lix restore
      run: npm ci
    - name: hxcpp setup
      run: |
        cd $(npx haxelib path hxcpp 2>&1 | head -n 1)
        npm install lix
        cd tools/hxcpp
        npx haxe compile.hxml
    - name: build
      run: npx haxe build.hxml
    - name: package
      run: |
        if [ -f "bin/cpp/atlas-creator.exe" ]; then
          tar -czvf ${{ matrix.os }}.tar.gz -C bin/cpp atlas-creator.exe
        else
          tar -czvf ${{ matrix.os }}.tar.gz -C bin/cpp atlas-creator
        fi
    - name: Upload Artefacts
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '${{ matrix.os }}.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: CI